// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAauobJvZkjdtYWUHbA7IfzXF5tYYoDLI',
    appId: '1:316879676984:web:2ee788581d642b98b5e8cd',
    messagingSenderId: '316879676984',
    projectId: 'coffeemanageapp-e1328',
    authDomain: 'coffeemanageapp-e1328.firebaseapp.com',
    databaseURL: 'https://coffeemanageapp-e1328-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffeemanageapp-e1328.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuZOryGtg5KghOxrRHd92IjCI7Phg3uhI',
    appId: '1:316879676984:android:76c01f3606e529a4b5e8cd',
    messagingSenderId: '316879676984',
    projectId: 'coffeemanageapp-e1328',
    databaseURL: 'https://coffeemanageapp-e1328-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffeemanageapp-e1328.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCER-FtzB11d-TnjWAlqU9omTOS_RDKITw',
    appId: '1:316879676984:ios:75e95c70dba6bbceb5e8cd',
    messagingSenderId: '316879676984',
    projectId: 'coffeemanageapp-e1328',
    databaseURL: 'https://coffeemanageapp-e1328-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffeemanageapp-e1328.appspot.com',
    iosBundleId: 'com.example.appCoffeeManage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCER-FtzB11d-TnjWAlqU9omTOS_RDKITw',
    appId: '1:316879676984:ios:ef3ed07e3c884e1fb5e8cd',
    messagingSenderId: '316879676984',
    projectId: 'coffeemanageapp-e1328',
    databaseURL: 'https://coffeemanageapp-e1328-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffeemanageapp-e1328.appspot.com',
    iosBundleId: 'com.example.appCoffeeManage.RunnerTests',
  );
}
